/*
 * This source file was generated by the Gradle 'init' task
 */
package com.smarthost.app

import com.smarthost.app.MessageUtils
import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class MessageUtilsTest {
    @Test fun testGetMessage() {
        assertEquals("Hello World!", MessageUtils.getMessage())
    }
}
