apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - name: backend
          env:
            - name: FRONTEND_HOST
              value: "localhost:3000"
            - name: PORT
              value: "8080"
          image: devops-coding-challenge_backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
        # - image: devops-coding-challenge_frontend:latest
        #   imagePullPolicy: IfNotPresent
        #   name: frontend
        #   ports:
        #     - containerPort: 80
        #       protocol: TCP
      restartPolicy: Always
