apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: devops-coding-challenge_frontend:latest
          imagePullPolicy: IfNotPresent
          name: frontend
          ports:
            - containerPort: 80
              protocol: TCP
      #     volumeMounts:
      #         - name: nginx-conf
      #           mountPath: /etc/nginx/nginx.conf
      #           subPath: nginx.conf
      #           readOnly: true
      # volumes:
      # - name: nginx-conf
      #   configMap:
      #     name: nginx-conf
      #     items:
      #       - key: nginx.conf
      #         path: nginx.conf
      restartPolicy: Always
